export const titleNames = {
    login: "login",
    MasterDashboard: "Masters",
    CustomerResult: "Add Customer",
    SupplaceResult: " Add Supply Place",
    CustomerHeaderResult: "Customer",
    CurrencyMasterResult: "Currency Master",
    UserAddResult: "User",
    PartMasterResult: "Add Item",
    SupplierResult: "Add Supplier",
    CustomerGroupResult: "CustomerGroup",
    ProjectNameResult: "Add Project Name",
    PartHeaderResult: "Item Master",
    PlaceOfSupplyResult: "PlaceOfSupply",
    BomModule: "BOM",
    ItemVsProcess: "Item vs Process Allocation",
    AddMasterResult: "Add Master",
    SalesResult: "Production Order Input",
    SalesResultAssembly: "Assembly Order Input",
    AddMachineResult: "Add Machine",
    SupplerResult: "Supplier Master",
    StoresItemMasterResult: "Item Master",
    SupplierVsItemMasterResult: "Supplier vs Item Master",
    ShiftMasterResult: "Shift Master",
    MachineOperatorResult: "Machine Operator",
    ProcessVsUOMResult: "Process vs UOM",
    PurchaseOrderGenerationModule: "Purchase Order",
    AuthoriseDocumentsModule: "Authorise Documents",
    SecondLevelAuthorizationModule: "Second Level Authorization",
    PurchaseBillAgainstPOModule: "Purchase Bill Against PO",
    MaterialIssueNote: "Material Issue Note",
    StoresRequestNote: "Stores Request Note",
    MinMaxStatusReport: "Min Max Status Report",
    SRNShortageReport: "SRN Shortage Report",
    ItemVsProcessView: "Item vs Process View",
    MinMaxConsumptionReport: "Min Max Consumption Report",
    PriceRevisionHistoryReport: "Price Revision History Report",
    NewSFGEntryModule: "SFG Entry",
    ViewSFGEntryModule: "View SFG",
    PurchaseOrderView: "Purchase Order View",
    MaterialIssueResult: "Material Issue",
    MaterialAllocationResult: "Material Allocation",
    AllocationComp: "Allocation",
    IssueComp: "Issue",
    QualityResults: "Quality Results",
    QualityTemplateResult: "Quality Template",
    PartProcessVsInspectionResult: "PartProcess vs Inspection",
    ProcessInspectionResult: "Process Inspection",
    InProcessFPIResult: "InProcess FPI",
    InProcessLPIResult: "InProcess LPI",
    InProcessReworkResult: "InProcess Rework",
    FPIReport: "FPI Report",
    ObservationReport: "Observation Report",
    ReworkReport: "Rework Report",
    LPIReport: "LPI Report",
    LPIModifiedReport: "LPI Modified Report",
    FPIModifiedReport: "FPI Modified Report",
    ObservationModifiedReport: "Observation Modified Report",
    ReworkModifiedReport: "Rework Modified Report",
    PurchaseOrderApprovalModule: "Purchase Order Approval",
    PriceRevisionApproval: "Price Revision Approval",
    RejectionAndRework: "Rejection And Rework Reason",
    DeptMasterList: "Department Master",
    SectionList: "Section List",
    ReportLabelList: "Report Label List",
    CheckTitleList: "Check Title List",
    CheckListList: "Check List",
    QualityResults: "Quality Results",
    QualityTemplateResult: "Quality Template",
    PartProcessVsInspectionResult: "Part Process vs Inspection",
    ProcessInspectionResult: "Process Inspection",
    InProcessFPIResult: "InProcess FPI",
    InProcessLPIResult: "InProcess LPI",
    InProcessReworkResult: "InProcess Rework",
    FPIReport: "FPI Report",
    ObservationReport: "Observation Report",
    ReworkReport: "Rework Report",
    LPIReport: "LPI Report",
    LPIModifiedReport: "LPI Modified Report",
    FPIModifiedReport: "FPI Modified Report",
    ObservationModifiedReport: "Observation Modified Report",
    ReworkModifiedReport: "Rework Modified Report",
    PurchaseOrderApprovalModule: "Purchase Order Approval",
    PriceRevisionApproval: "Price Revision Approval",
    AssignRightsModal: "Assign Rights",
    MenuRightsResult: "Menu Rights",
    GroupMasterResult: "Group Master",
    SfgVarificationResult: "SFG Verification",
    SfgViewResult: "SFG View",
    SfgVendorProcessResult: "SFG Supplier Process",
    ViewSfgVendorProcessResult: "View SFG Supplier Process",
    RMBOIIndentReportResult: "RMBOI Indent Report",
    MachinePlanningTab: "Machine Planning",
    FIMMasterResult: "FIM Master",
    CSLimportResult: "CSL import",
    SOBimportResult: "SOB import",
    InProcessIn: "InProcess In",
    FPIReportTitle: "FPI Report",
    OrderPlaningResult: "Order Planning",
    OrderTypeMasterResult: "Order Type Master",
    ToolResult: "Add Tool",
    ProcessVsToolResult: "Part No vs Process vs Tool",
    ToolMonitoringResult: "Tool Monitoring",
    ToolGrindingResult: "Tool Grinding",
    ToolUsageReport: "Tool Report",
    DispatchResult: "Dispatch",
    CDispatchOrderResult: "Customer Del Note",
    VendorDispatchOrderResult: "Supplier Del Note",
    DeliveryOrderStatusResult: "Del Note Status",
    CreateDeliveryOrderResult: "Create Del Note",
    HolidayMasterResult: "Holiday Master",
    NpdResult: "NPD Add Drawing",
    DeletLog: "NPD Deleted Log",
    PlanReportResult: "Plan Report",
    MachinePlaning: "Machine Planing",
    FileTypeResult: "File Type",
    NPDPlanResult: "NPD Plan",
    AccMasterList: "Transport Master",
    AccDispatchList: "Dispatch Master",
    PurchaseEntryList: "Purchase Order Entry",
    GSTSalesList: "GST Sales Invoice",
    EinvoicingList: "E Invoicing",
    NonRetrnableDcList: "Non Returnable DC",
    CustDcList: "Customer DC",
    QualityMstList: "Quality Master",
    GanttChartModule: "Order Plannig",
    MkdResult: "MKD",
    JabCardView: "Job Card",
    ScrapModule: "Scrap",
    ScrapReport: "Scrap Report",
    ProductMaster: "Product Master",
    ProductionResult: "NPD Order Input",
    PlanningStoreRequestNote: "Planning SRN",
    SrnShortClosed: "SRN ShortClosed",
    FGItemList: "Map Customer PO & DC",
    FGItemViewResult: 'Map Customer PO & DC',
    NewMaterialIsseResult: 'Material Issue',
    NewSfgVarificationResult: 'SFG Varification',
    MaterialReturnNoteList: 'Material Return Note',
    JobWorkIssueModal: 'Job Work Issue',
    NewPurchaseOrderEntry: 'PO - Sales Order Entry',
    NewNRDCEntry: 'Non Returnable DC',
    MaterialReturnNoteList: 'Material Return Note',
    NewGstInvoice: 'GST Sales Invoice',
    PriceChangeResult: 'Price Change Note',
    ReportTabsList: "Plan Report"
}